In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn import manifold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
# from xgboost import XGBClassifier, XGBRFClassifier
# from xgboost import plot_tree, plot_importance
from scipy.spatial.distance import pdist
from sklearn.neighbors import BallTree
from sklearn.neighbors import KDTree
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv("./data/features_3_sec.csv")
# data = data.iloc[0:, 2:]
data = data.drop(columns='length',axis=1)
print(data.shape)
data.head(10)

(9990, 59)


filename  chroma_stft_mean  chroma_stft_var  rms_mean   rms_var  \
0  blues.00000.0.wav          0.335406         0.091048  0.130405  0.003521   
1  blues.00000.1.wav          0.343065         0.086147  0.112699  0.001450   
2  blues.00000.2.wav          0.346815         0.092243  0.132003  0.004620   
3  blues.00000.3.wav          0.363639         0.086856  0.132565  0.002448   
4  blues.00000.4.wav          0.335579         0.088129  0.143289  0.001701   
5  blues.00000.5.wav          0.376670         0.089702  0.132618  0.003583   
6  blues.00000.6.wav          0.379909         0.088827  0.130335  0.003166   
7  blues.00000.7.wav          0.331880         0.092119  0.140600  0.002546   
8  blues.00000.8.wav          0.347877         0.094209  0.133130  0.002538   
9  blues.00000.9.wav          0.358061         0.082957  0.115312  0.001846   

   spectral_centroid_mean  spectral_centroid_var  spectral_bandwidth_mean  \
0             1773.065032          167541.630869              1972.744388   
1             1816.693777           90525.690866              2010.051501   
2             1788.539719          111407.437613              2084.565132   
3             1655.289045          111952.284517              1960.039988   
4             1630.656199           79667.267654              1948.503884   
5             1994.915219          211700.619569              2152.767854   
6             1962.150096          177443.070045              2146.503479   
7             1701.890924           35678.130616              1979.387612   
8             1746.473502          138073.931244              1887.619723   
9             1763.948942           61493.423121              1874.195710   

   spectral_bandwidth_var  rolloff_mean  ...  mfcc16_var  mfcc17_mean  \
0           117335.771563   3714.560359  ...   39.687145    -3.241280   
1            65671.875673   3869.682242  ...   64.748276    -6.055294   
2            75124.921716   3997.639160  ...   67.336563    -1.768610   
3            82913.639269   3568.300218  ...   47.739452    -3.841155   
4            60204.020268   3469.992864  ...   30.336359     0.664582   
5            74263.873102   4371.985614  ...   31.448069    -3.448373   
6            98020.541422   4325.026668  ...   33.954071    -2.068194   
7            36670.725886   3625.280386  ...   38.456211    -3.637886   
8           117069.920049   3586.934721  ...   44.311455    -4.370029   
9            51944.921435   3505.522649  ...   43.967834    -3.448304   

   mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  mfcc19_var  mfcc20_mean  \
0   36.488243     0.722209   38.099152    -5.050335   33.618073    -0.243027   
1   40.677654     0.159015   51.264091    -2.837699   97.030830     5.784063   
2   28.348579     2.378768   45.717648    -1.938424   53.050835     2.517375   
3   28.337118     1.218588   34.770935    -3.580352   50.836224     3.630866   
4   45.880913     1.689446   51.363583    -3.392489   26.738789     0.536961   
5   34.284130    -0.416165   40.791092    -3.649625   32.457901     3.025218   
6   25.623655     1.428141   47.957699    -3.267124   39.382240     3.276939   
7   24.530296    -0.105148   26.716150    -2.016985   23.150423     0.210787   
8   29.873167     2.114592   33.843155    -2.264663   80.812393     3.758598   
9   48.671944     0.099792   41.839546    -7.677177   96.253654     0.791776   

   mfcc20_var  label  
0   43.771767  blues  
1   59.943081  blues  
2   33.105122  blues  
3   32.023678  blues  
4   29.146694  blues  
5   28.892687  blues  
6   25.999132  blues  
7   42.512966  blues  
8   97.618835  blues  
9   40.416420  blues  

[10 rows x 59 columns]

In [3]:
tdata = data.drop(columns='label',axis=1)
tdata = tdata.drop(columns='filename',axis=1)
X = np.array(tdata.values.tolist())

In [4]:
q = 1234
qlabel = data.iloc[q]['label']
sx = preprocessing.StandardScaler().fit(X)
ssx = sx.transform(X)
tree = KDTree(ssx, leaf_size=50)
dist, ind = tree.query([ssx[q]], k=6)
print(dist)
print(ind)
data.iloc[ind[0]]

[[0.         5.00424143 5.20503481 5.34363824 5.38013135 5.65568941]]
[[1234 1233 1050 5220 1099 1367]]


filename  chroma_stft_mean  chroma_stft_var  rms_mean  \
1234  classical.00023.4.wav          0.316787         0.079305  0.017781   
1233  classical.00023.3.wav          0.255868         0.082603  0.018314   
1050  classical.00005.0.wav          0.271920         0.084546  0.052777   
5220       jazz.00022.8.wav          0.208365         0.081428  0.044650   
1099  classical.00009.9.wav          0.337535         0.077901  0.031638   
1367  classical.00036.7.wav          0.310709         0.090485  0.008066   

       rms_var  spectral_centroid_mean  spectral_centroid_var  \
1234  0.000013             1139.274329            8682.867286   
1233  0.000008             1049.869257           13880.915691   
1050  0.000319             1208.629552           19744.146666   
5220  0.000092             1302.019067           48869.934033   
1099  0.000021             1121.615980           20947.724470   
1367  0.000007             1062.129769            6257.297517   

      spectral_bandwidth_mean  spectral_bandwidth_var  rolloff_mean  ...  \
1234              1482.744242             5977.418753   2199.202599  ...   
1233              1458.444164             9192.430539   1965.732985  ...   
1050              1517.452252            16067.542964   2409.234150  ...   
5220              1809.318034            47167.341041   2530.234187  ...   
1099              1535.541739            19720.558963   2385.050706  ...   
1367              1262.381181             3855.761134   1874.051232  ...   

      mfcc16_var  mfcc17_mean  mfcc17_var  mfcc18_mean  mfcc18_var  \
1234   38.608368    11.965379   34.490784    17.566053   75.889496   
1233   32.343872    -2.710440  113.422203     9.411086   27.686707   
1050   55.666405     5.550305   40.928753     4.587184   49.594013   
5220   31.334616    11.725071   37.855701    10.841774   34.716068   
1099   52.692497     2.901621   29.563099     6.893927   29.100264   
1367   34.688461    17.781878   25.851328     6.823909   61.345043   

      mfcc19_mean  mfcc19_var  mfcc20_mean  mfcc20_var      label  
1234    -1.704877   18.241920    -2.981100   71.229057  classical  
1233     0.854646   73.655754    -4.758855   59.204552  classical  
1050     1.364833   36.368469     0.964094   25.334044  classical  
5220     0.072980   40.464264   -11.230765   63.772575       jazz  
1099     1.041602   32.419998     0.690517   40.686699  classical  
1367    -4.022739   63.366631    -9.965539   26.109259  classical  

[6 rows x 59 columns]

In [5]:
sx = preprocessing.StandardScaler().fit(X)
ssx = sx.transform(X)
tree = BallTree(ssx, leaf_size=50)
acc = 0
rnum = 5
for q in range(9990):
    qlabel = data.iloc[q]['label']
    dist, ind = tree.query([ssx[q]], k=rnum+1)
    matched = data.iloc[ind[0]].where(data.label==qlabel).dropna(axis=0, how='all').shape[0]
    acc = acc + matched -1
acc /= (9990*rnum)
print(acc)

KeyboardInterrupt: 

In [ ]:
sx = preprocessing.StandardScaler().fit(X)
ssx = sx.transform(X)
tree = BallTree(ssx, leaf_size=50)
acc = 0
rnum = 7
for q in range(9990):
    qlabel = data.iloc[q]['label']
    dist, ind = tree.query([ssx[q]], k=rnum+1)
    matched = data.iloc[ind[0]].where(data.label==qlabel).dropna(axis=0, how='all').shape[0]
    acc = acc + matched -1
    if q%50==0:
        print(str(q) + " done")
acc /= (9990*rnum)
print(acc)

In [5]:
sx = preprocessing.StandardScaler().fit(X)
ssx = sx.transform(X)
tree = BallTree(ssx, leaf_size=50)
acc = 0
rnum = 5
for q in range(9990):
    qlabel = data.iloc[q]['label']
    dist, ind = tree.query([ssx[q]], k=rnum+1)
    res = data.iloc[ind[0]]
    tempstr = res.iat[0,0].split('.')
    fname = tempstr[0] + "." + tempstr[1]
    flag = res['filename'].str.contains(fname)
    matched = res[flag].shape[0]
    acc = acc + matched -1
    if q%50==0:
        print(str(q) + " done")
acc /= (9990*rnum)
print(acc)

0 done
50 done
100 done
150 done
200 done
250 done
300 done
350 done
400 done
450 done
500 done
550 done
600 done
650 done
700 done
750 done
800 done
850 done
900 done
950 done
1000 done
1050 done
1100 done
1150 done
1200 done
1250 done
1300 done
1350 done
1400 done
1450 done
1500 done
1550 done
1600 done
1650 done
1700 done
1750 done
1800 done
1850 done
1900 done
1950 done
2000 done
2050 done
2100 done
2150 done
2200 done
2250 done
2300 done
2350 done
2400 done
2450 done
2500 done
2550 done
2600 done
2650 done
2700 done
2750 done
2800 done
2850 done
2900 done
2950 done
3000 done
3050 done
3100 done
3150 done
3200 done
3250 done
3300 done
3350 done
3400 done
3450 done
3500 done
3550 done
3600 done
3650 done
3700 done
3750 done
3800 done
3850 done
3900 done
3950 done
4000 done
4050 done
4100 done
4150 done
4200 done
4250 done
4300 done
4350 done
4400 done
4450 done
4500 done
4550 done
4600 done
4650 done
4700 done
4750 done
4800 done
4850 done
4900 done
4950 done
5000 done
5050 done
510

In [ ]:
sx = preprocessing.StandardScaler().fit(X)
ssx = sx.transform(X)
tree = BallTree(ssx, leaf_size=50)
acc = 0
rnum = 7
for q in range(9990):
    qlabel = data.iloc[q]['label']
    dist, ind = tree.query([ssx[q]], k=rnum+1)
    res = data.iloc[ind[0]]
    tempstr = res.iat[0,0].split('.')
    fname = tempstr[0] + "." + tempstr[1]
    flag = res['filename'].str.contains(fname)
    matched = res[flag].shape[0]
    acc = acc + matched -1
    if q%50==0:
        print(str(q) + " done")
acc /= (9990*rnum)
print(acc)

In [18]:
sx = preprocessing.StandardScaler().fit(X)
ssx = sx.transform(X)
tree = BallTree(ssx, leaf_size=50)
acc = [0]*10
rnum = 5
for q in range(9990):
    qlabel = data.iloc[q]['label']
    dist, ind = tree.query([ssx[q]], k=rnum+1)
    res = data.iloc[ind[0]]
    tempstr = res.iat[0,0].split('.')
    fname = tempstr[0] + "." + tempstr[1]
    flag = res['filename'].str.contains(fname)
    matched = res[flag].shape[0]
    acc[q//999] = acc[q//999] + matched -1
    if q%50==0:
        print(str(q) + " done")
res = [itr/(999*rnum) for itr in acc]
print(res)


0 done
50 done
100 done
150 done
200 done
250 done
300 done
350 done
400 done
450 done
500 done
550 done
600 done
650 done
700 done
750 done
800 done
850 done
900 done
950 done
1000 done
1050 done
1100 done
1150 done
1200 done
1250 done
1300 done
1350 done
1400 done
1450 done
1500 done
1550 done
1600 done
1650 done
1700 done
1750 done
1800 done
1850 done
1900 done
1950 done
2000 done
2050 done
2100 done
2150 done
2200 done
2250 done
2300 done
2350 done
2400 done
2450 done
2500 done
2550 done
2600 done
2650 done
2700 done
2750 done
2800 done
2850 done
2900 done
2950 done
3000 done
3050 done
3100 done
3150 done
3200 done
3250 done
3300 done
3350 done
3400 done
3450 done
3500 done
3550 done
3600 done
3650 done
3700 done
3750 done
3800 done
3850 done
3900 done
3950 done
4000 done
4050 done
4100 done
4150 done
4200 done
4250 done
4300 done
4350 done
4400 done
4450 done
4500 done
4550 done
4600 done
4650 done
4700 done
4750 done
4800 done
4850 done
4900 done
4950 done
5000 done
5050 done
510

# 10 KDtree

In [19]:
map_label = {"blues":0, "classical":1, "country":2, "disco":3, "hiphop":4, "jazz":5, "metal":6, "pop":7, "reggae":8, "rock":9}
classes=["blues", "classical", "country", "disco", "hiphop", "jazz", "metal", "pop", "reggae", "rock"]
music_lib = {}
for i in range(10):
    music_lib[classes[i]] = data.where(data.label==classes[i]).dropna(axis=0, how='all')
tdata = data.drop(columns='label',axis=1)
tdata = tdata.drop(columns='filename',axis=1)
X = np.array(tdata.values.tolist())

{'blues':               filename  chroma_stft_mean  chroma_stft_var  rms_mean   rms_var  \
 0    blues.00000.0.wav          0.335406         0.091048  0.130405  0.003521   
 1    blues.00000.1.wav          0.343065         0.086147  0.112699  0.001450   
 2    blues.00000.2.wav          0.346815         0.092243  0.132003  0.004620   
 3    blues.00000.3.wav          0.363639         0.086856  0.132565  0.002448   
 4    blues.00000.4.wav          0.335579         0.088129  0.143289  0.001701   
 ..                 ...               ...              ...       ...       ...   
 995  blues.00099.5.wav          0.403316         0.082238  0.105042  0.006341   
 996  blues.00099.6.wav          0.341371         0.084091  0.173131  0.005539   
 997  blues.00099.7.wav          0.378564         0.094337  0.095310  0.005790   
 998  blues.00099.8.wav          0.381282         0.086331  0.082442  0.006571   
 999  blues.00099.9.wav          0.359969         0.083549  0.123457  0.002840   
 
     

In [28]:
tdata = data.drop(columns='label',axis=1)
tdata = tdata.drop(columns='filename',axis=1)
X = np.array(tdata.values.tolist())
slib = preprocessing.StandardScaler().fit(X)
sslib = slib.transform(X)
label_tree = {}
for i in range(10):
    label_tree[classes[i]] = KDTree(sslib[i*999:(i+1)*999], leaf_size=50)

In [29]:
q =2345
qdata = sslib[q]
data.iloc[[q]]
qlabel = data.iloc[q]['label']
print(qlabel)
dist, ind = label_tree[qlabel].query([qdata], k=6)
print(dist)
print(ind)
temp = music_lib[qlabel].iloc[ind[0]]
temp.head()

country
[[0.         4.25556343 4.25765772 4.27582353 4.59435886 4.59708648]]
[[347 351 349 348 350 353]]


filename  chroma_stft_mean  chroma_stft_var  rms_mean  \
2345  country.00035.0.wav          0.413837         0.082309  0.102332   
2349  country.00035.4.wav          0.407691         0.073052  0.100665   
2347  country.00035.2.wav          0.403109         0.074177  0.094093   
2346  country.00035.1.wav          0.365637         0.077258  0.106882   
2348  country.00035.3.wav          0.387402         0.081486  0.105416   

       rms_var  spectral_centroid_mean  spectral_centroid_var  \
2345  0.001690             2216.462209          368949.735328   
2349  0.001069             2239.843658          205035.997133   
2347  0.001146             2287.916467          660447.635858   
2346  0.000878             2145.482961          390050.104997   
2348  0.001383             2181.152325          226244.411138   

      spectral_bandwidth_mean  spectral_bandwidth_var  rolloff_mean  ...  \
2345              2491.165572           167046.247697   4404.782339  ...   
2349              2448.180760           122655.162064   4291.567383  ...   
2347              2482.156241           183787.086917   4435.674204  ...   
2346              2489.790671           121917.755092   4224.980093  ...   
2348              2473.281819           121700.851301   4253.304537  ...   

      mfcc16_var  mfcc17_mean  mfcc17_var  mfcc18_mean  mfcc18_var  \
2345   53.328480    -5.289549   33.108322    -8.295418   51.656910   
2349   17.425480    -2.731469   22.418818    -6.565702   34.013844   
2347   22.279987    -4.421815   44.124851    -5.296407   53.796848   
2346   57.143478    -8.165647   38.545807    -9.030909   21.521551   
2348   56.883465    -0.880667   38.793194    -7.677799   52.296341   

      mfcc19_mean  mfcc19_var  mfcc20_mean  mfcc20_var    label  
2345    -3.266910   26.757587     0.265015   29.919449  country  
2349    -2.890094   43.714649    -3.753485   37.077629  country  
2347    -1.156787   37.256516    -5.233200   21.013763  country  
2346    -3.384717   36.084637    -4.796948   29.269058  country  
2348    -5.011296   34.629517    -1.758947   24.356316  country  

[5 rows x 59 columns]

In [22]:
tempstr = temp.iat[0,0].split('.')
fname = tempstr[0] + "." + tempstr[1]
flag = temp['filename'].str.contains(fname)
temp[flag].head()

filename  chroma_stft_mean  chroma_stft_var  rms_mean  \
2345  country.00035.0.wav          0.413837         0.082309  0.102332   
2349  country.00035.4.wav          0.407691         0.073052  0.100665   
2347  country.00035.2.wav          0.403109         0.074177  0.094093   
2346  country.00035.1.wav          0.365637         0.077258  0.106882   
2348  country.00035.3.wav          0.387402         0.081486  0.105416   

       rms_var  spectral_centroid_mean  spectral_centroid_var  \
2345  0.001690             2216.462209          368949.735328   
2349  0.001069             2239.843658          205035.997133   
2347  0.001146             2287.916467          660447.635858   
2346  0.000878             2145.482961          390050.104997   
2348  0.001383             2181.152325          226244.411138   

      spectral_bandwidth_mean  spectral_bandwidth_var  rolloff_mean  ...  \
2345              2491.165572           167046.247697   4404.782339  ...   
2349              2448.180760           122655.162064   4291.567383  ...   
2347              2482.156241           183787.086917   4435.674204  ...   
2346              2489.790671           121917.755092   4224.980093  ...   
2348              2473.281819           121700.851301   4253.304537  ...   

      mfcc16_var  mfcc17_mean  mfcc17_var  mfcc18_mean  mfcc18_var  \
2345   53.328480    -5.289549   33.108322    -8.295418   51.656910   
2349   17.425480    -2.731469   22.418818    -6.565702   34.013844   
2347   22.279987    -4.421815   44.124851    -5.296407   53.796848   
2346   57.143478    -8.165647   38.545807    -9.030909   21.521551   
2348   56.883465    -0.880667   38.793194    -7.677799   52.296341   

      mfcc19_mean  mfcc19_var  mfcc20_mean  mfcc20_var    label  
2345    -3.266910   26.757587     0.265015   29.919449  country  
2349    -2.890094   43.714649    -3.753485   37.077629  country  
2347    -1.156787   37.256516    -5.233200   21.013763  country  
2346    -3.384717   36.084637    -4.796948   29.269058  country  
2348    -5.011296   34.629517    -1.758947   24.356316  country  

[5 rows x 59 columns]

In [23]:
acc = 0
rnum = 5
for q in range(9990):
    qlabel = data.iloc[q]['label']
    dist, ind = label_tree[qlabel].query([sslib[q]], k=rnum+1)
    res = data.iloc[ind[0]]
    tempstr = res.iat[0,0].split('.')
    fname = tempstr[0] + "." + tempstr[1]
    flag = res['filename'].str.contains(fname)
    matched = res[flag].shape[0]
    acc = acc + matched -1
    if q%50==0:
        print(str(q) + " done")
acc /= (9990*rnum)
print(acc)

0 done
50 done
100 done
150 done
200 done
250 done
300 done
350 done
400 done
450 done
500 done
550 done
600 done
650 done
700 done
750 done
800 done
850 done
900 done
950 done
1000 done
1050 done
1100 done
1150 done
1200 done
1250 done
1300 done
1350 done
1400 done
1450 done
1500 done
1550 done
1600 done
1650 done
1700 done
1750 done
1800 done
1850 done
1900 done
1950 done
2000 done
2050 done
2100 done
2150 done
2200 done
2250 done
2300 done
2350 done
2400 done
2450 done
2500 done
2550 done
2600 done
2650 done
2700 done
2750 done
2800 done
2850 done
2900 done
2950 done
3000 done
3050 done
3100 done
3150 done
3200 done
3250 done
3300 done
3350 done
3400 done
3450 done
3500 done
3550 done
3600 done
3650 done
3700 done
3750 done
3800 done
3850 done
3900 done
3950 done
4000 done
4050 done
4100 done
4150 done
4200 done
4250 done
4300 done
4350 done
4400 done
4450 done
4500 done
4550 done
4600 done
4650 done
4700 done
4750 done
4800 done
4850 done
4900 done
4950 done
5000 done
5050 done
510

In [15]:
acc = [0]*10
rnum = 5
for q in range(9990):
    qlabel = data.iloc[q]['label']
    dist, ind = label_tree[qlabel].query([sslib[q]], k=rnum+1)
    res = data.iloc[ind[0]]
    tempstr = res.iat[0,0].split('.')
    fname = tempstr[0] + "." + tempstr[1]
    flag = res['filename'].str.contains(fname)
    matched = res[flag].shape[0]
    acc[q//999] = acc[q//999] + matched -1
    if q%50==0:
        print(str(q) + " done")
res = [itr/(999*5) for itr in acc]
print(acc)


0 done
50 done
100 done
150 done
200 done
250 done
300 done
350 done
400 done
450 done
500 done
550 done
600 done
650 done
700 done
750 done
800 done
850 done
900 done
950 done
1000 done
1050 done
1100 done
1150 done
1200 done
1250 done
1300 done
1350 done
1400 done
1450 done
1500 done
1550 done
1600 done
1650 done
1700 done
1750 done
1800 done
1850 done
1900 done
1950 done
2000 done
2050 done
2100 done
2150 done
2200 done
2250 done
2300 done
2350 done
2400 done
2450 done
2500 done
2550 done
2600 done
2650 done
2700 done
2750 done
2800 done
2850 done
2900 done
2950 done
3000 done
3050 done
3100 done
3150 done
3200 done
3250 done
3300 done
3350 done
3400 done
3450 done
3500 done
3550 done
3600 done
3650 done
3700 done
3750 done
3800 done
3850 done
3900 done
3950 done
4000 done
4050 done
4100 done
4150 done
4200 done
4250 done
4300 done
4350 done
4400 done
4450 done
4500 done
4550 done
4600 done
4650 done
4700 done
4750 done
4800 done
4850 done
4900 done
4950 done
5000 done
5050 done
510

In [16]:
res

[0.5857857857857858,
 0.23423423423423423,
 0.2782782782782783,
 0.39579579579579577,
 0.4844844844844845,
 0.3199199199199199,
 0.46546546546546547,
 0.3299299299299299,
 0.5023023023023023,
 0.6]

# 30->3

In [8]:
data_30 = pd.read_csv("./data/features_30_sec.csv")
data_30 = data_30.drop(columns='length',axis=1)
print(data_30.shape)
data_30.head(10)

(1000, 59)


filename  chroma_stft_mean  chroma_stft_var  rms_mean   rms_var  \
0  blues.00000.wav          0.350088         0.088757  0.130228  0.002827   
1  blues.00001.wav          0.340914         0.094980  0.095948  0.002373   
2  blues.00002.wav          0.363637         0.085275  0.175570  0.002746   
3  blues.00003.wav          0.404785         0.093999  0.141093  0.006346   
4  blues.00004.wav          0.308526         0.087841  0.091529  0.002303   
5  blues.00005.wav          0.302456         0.087532  0.103494  0.003981   
6  blues.00006.wav          0.291328         0.093981  0.141874  0.008803   
7  blues.00007.wav          0.307955         0.092903  0.131822  0.005531   
8  blues.00008.wav          0.408879         0.086512  0.142416  0.001507   
9  blues.00009.wav          0.273950         0.092316  0.081314  0.004347   

   spectral_centroid_mean  spectral_centroid_var  spectral_bandwidth_mean  \
0             1784.165850           1.297741e+05              2002.449060   
1             1530.176679           3.758501e+05              2039.036516   
2             1552.811865           1.564676e+05              1747.702312   
3             1070.106615           1.843559e+05              1596.412872   
4             1835.004266           3.433999e+05              1748.172116   
5             1831.993940           1.030482e+06              1729.653287   
6             1459.366472           4.378594e+05              1389.009131   
7             1451.667066           4.495682e+05              1577.270941   
8             1719.368948           1.632828e+05              2031.740381   
9             1817.150863           2.982361e+05              1973.773306   

   spectral_bandwidth_var  rolloff_mean  ...  mfcc16_var  mfcc17_mean  \
0            85882.761315   3805.839606  ...   52.420910    -1.690215   
1           213843.755497   3550.522098  ...   55.356403    -0.731125   
2            76254.192257   3042.260232  ...   40.598766    -7.729093   
3           166441.494769   2184.745799  ...   44.427753    -3.319597   
4            88445.209036   3579.757627  ...   86.099236    -5.454034   
5           201910.508633   3481.517592  ...   72.549225    -1.838263   
6           185023.239545   2795.610963  ...   83.248245   -10.913176   
7           168211.938804   2954.836760  ...   70.438438   -10.568935   
8           105542.718193   3782.316288  ...   50.563751    -7.041824   
9           114070.112591   3943.490565  ...   59.314602    -1.916804   

   mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  mfcc19_var  mfcc20_mean  \
0   36.524071    -0.408979   41.597103    -2.303523   55.062923     1.221291   
1   60.314529     0.295073   48.120598    -0.283518   51.106190     0.531217   
2   47.639427    -1.816407   52.382141    -3.439720   46.639660    -2.231258   
3   50.206673     0.636965   37.319130    -0.619121   37.259739    -3.407448   
4   75.269707    -0.916874   53.613918    -4.404827   62.910812   -11.703234   
5   68.702026    -2.783800   42.447453    -3.047909   39.808784    -8.109991   
6   56.902153    -6.971336   38.231800    -3.436505   48.235741    -6.483466   
7   52.090893   -10.784515   60.461330    -4.690678   65.547516    -8.630722   
8   28.894934     2.695248   36.889568     3.412305   33.698597    -2.715692   
9   58.418438    -2.292661   83.205231     2.881967   77.082222    -4.235203   

   mfcc20_var  label  
0   46.936035  blues  
1   45.786282  blues  
2   30.573025  blues  
3   31.949339  blues  
4   55.195160  blues  
5   46.311005  blues  
6   70.170364  blues  
7   56.401436  blues  
8   36.418430  blues  
9   91.468811  blues  

[10 rows x 59 columns]

In [9]:
tdata_30 = data_30.drop(columns='label',axis=1)
tdata_30 = tdata_30.drop(columns='filename',axis=1)
X = np.array(tdata_30.values.tolist())
slib_30 = preprocessing.StandardScaler().fit(X)
sslib_30 = slib.transform(X)

In [14]:
q =111
qdata = sslib_30[q]
data_30.iloc[[q]]
qlabel = data_30.iloc[q]['label']
print(qlabel)
dist, ind = label_tree[qlabel].query([qdata], k=6)
print(dist)
print(ind)
music_lib[qlabel].iloc[ind[0]]

classical
[[3.99294674 4.12296973 4.23931728 4.4898052  4.51270557 4.53998495]]
[[741 149 814 188 314 742]]


filename  chroma_stft_mean  chroma_stft_var  rms_mean  \
1741  classical.00074.3.wav          0.220486         0.081572  0.043942   
1149  classical.00014.9.wav          0.248113         0.083928  0.022592   
1814  classical.00081.6.wav          0.268047         0.084280  0.016723   
1188  classical.00018.8.wav          0.238047         0.080085  0.020968   
1314  classical.00031.4.wav          0.281305         0.089618  0.025753   
1742  classical.00074.4.wav          0.238398         0.084143  0.018772   

       rms_var  spectral_centroid_mean  spectral_centroid_var  \
1741  0.000575             1142.903955           67811.621754   
1149  0.000096             1014.919815           20510.004329   
1814  0.000038             1193.259095           37613.721561   
1188  0.000039              750.966960           22496.116902   
1314  0.000153              928.678645           25483.322408   
1742  0.000485             1373.647763          127837.013814   

      spectral_bandwidth_mean  spectral_bandwidth_var  rolloff_mean  ...  \
1741              1404.067071            76121.026554   2092.613244  ...   
1149              1191.690910            20321.112584   1856.990309  ...   
1814              1538.348899            31559.463210   2142.056791  ...   
1188               908.824298            11512.725043   1181.675931  ...   
1314              1241.905645            33254.126169   1664.102502  ...   
1742              1545.734405            69757.142115   2645.602464  ...   

      mfcc16_var  mfcc17_mean  mfcc17_var  mfcc18_mean  mfcc18_var  \
1741   30.178453     3.312286   50.542389     0.971022   55.582973   
1149   73.419426     3.742619   46.322987     3.529058  110.688332   
1814   31.373814    -2.285781   36.476967    -0.837594   50.098961   
1188   29.714142    -0.942692   28.150362    -6.796019   24.159954   
1314   55.064411    -2.019715   68.745796    -2.364160   65.524475   
1742   74.813889     1.956545   92.146751     0.987430   51.123528   

      mfcc19_mean  mfcc19_var  mfcc20_mean  mfcc20_var      label  
1741     0.962725   65.963654     6.556884   71.874352  classical  
1149     7.620941  107.350151    -3.541866   75.716080  classical  
1814     2.216539   87.591164     4.239258  106.327309  classical  
1188     1.638290   71.389366     8.196926   63.338776  classical  
1314     0.401647   66.796623     0.381216   93.805534  classical  
1742    -1.198816   76.373543    -4.821969   81.243500  classical  

[6 rows x 59 columns]