In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn import manifold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
# from xgboost import XGBClassifier, XGBRFClassifier
# from xgboost import plot_tree, plot_importance
from scipy.spatial.distance import pdist
from sklearn.neighbors import BallTree
from sklearn.neighbors import KDTree
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv("./data/features_30_sec.csv")
# data = data.iloc[0:, 2:]
data = data.drop(columns='length',axis=1)
print(data.shape)
data.head(10)

(1000, 59)


filename  chroma_stft_mean  chroma_stft_var  rms_mean   rms_var  \
0  blues.00000.wav          0.350088         0.088757  0.130228  0.002827   
1  blues.00001.wav          0.340914         0.094980  0.095948  0.002373   
2  blues.00002.wav          0.363637         0.085275  0.175570  0.002746   
3  blues.00003.wav          0.404785         0.093999  0.141093  0.006346   
4  blues.00004.wav          0.308526         0.087841  0.091529  0.002303   
5  blues.00005.wav          0.302456         0.087532  0.103494  0.003981   
6  blues.00006.wav          0.291328         0.093981  0.141874  0.008803   
7  blues.00007.wav          0.307955         0.092903  0.131822  0.005531   
8  blues.00008.wav          0.408879         0.086512  0.142416  0.001507   
9  blues.00009.wav          0.273950         0.092316  0.081314  0.004347   

   spectral_centroid_mean  spectral_centroid_var  spectral_bandwidth_mean  \
0             1784.165850           1.297741e+05              2002.449060   
1             1530.176679           3.758501e+05              2039.036516   
2             1552.811865           1.564676e+05              1747.702312   
3             1070.106615           1.843559e+05              1596.412872   
4             1835.004266           3.433999e+05              1748.172116   
5             1831.993940           1.030482e+06              1729.653287   
6             1459.366472           4.378594e+05              1389.009131   
7             1451.667066           4.495682e+05              1577.270941   
8             1719.368948           1.632828e+05              2031.740381   
9             1817.150863           2.982361e+05              1973.773306   

   spectral_bandwidth_var  rolloff_mean  ...  mfcc16_var  mfcc17_mean  \
0            85882.761315   3805.839606  ...   52.420910    -1.690215   
1           213843.755497   3550.522098  ...   55.356403    -0.731125   
2            76254.192257   3042.260232  ...   40.598766    -7.729093   
3           166441.494769   2184.745799  ...   44.427753    -3.319597   
4            88445.209036   3579.757627  ...   86.099236    -5.454034   
5           201910.508633   3481.517592  ...   72.549225    -1.838263   
6           185023.239545   2795.610963  ...   83.248245   -10.913176   
7           168211.938804   2954.836760  ...   70.438438   -10.568935   
8           105542.718193   3782.316288  ...   50.563751    -7.041824   
9           114070.112591   3943.490565  ...   59.314602    -1.916804   

   mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  mfcc19_var  mfcc20_mean  \
0   36.524071    -0.408979   41.597103    -2.303523   55.062923     1.221291   
1   60.314529     0.295073   48.120598    -0.283518   51.106190     0.531217   
2   47.639427    -1.816407   52.382141    -3.439720   46.639660    -2.231258   
3   50.206673     0.636965   37.319130    -0.619121   37.259739    -3.407448   
4   75.269707    -0.916874   53.613918    -4.404827   62.910812   -11.703234   
5   68.702026    -2.783800   42.447453    -3.047909   39.808784    -8.109991   
6   56.902153    -6.971336   38.231800    -3.436505   48.235741    -6.483466   
7   52.090893   -10.784515   60.461330    -4.690678   65.547516    -8.630722   
8   28.894934     2.695248   36.889568     3.412305   33.698597    -2.715692   
9   58.418438    -2.292661   83.205231     2.881967   77.082222    -4.235203   

   mfcc20_var  label  
0   46.936035  blues  
1   45.786282  blues  
2   30.573025  blues  
3   31.949339  blues  
4   55.195160  blues  
5   46.311005  blues  
6   70.170364  blues  
7   56.401436  blues  
8   36.418430  blues  
9   91.468811  blues  

[10 rows x 59 columns]

In [3]:
data_3 = pd.read_csv("./data/features_3_sec.csv")
# data = data.iloc[0:, 2:]
data_3 = data_3.drop(columns='length',axis=1)
print(data_3.shape)
data_3.head(10)

(9990, 59)


filename  chroma_stft_mean  chroma_stft_var  rms_mean   rms_var  \
0  blues.00000.0.wav          0.335406         0.091048  0.130405  0.003521   
1  blues.00000.1.wav          0.343065         0.086147  0.112699  0.001450   
2  blues.00000.2.wav          0.346815         0.092243  0.132003  0.004620   
3  blues.00000.3.wav          0.363639         0.086856  0.132565  0.002448   
4  blues.00000.4.wav          0.335579         0.088129  0.143289  0.001701   
5  blues.00000.5.wav          0.376670         0.089702  0.132618  0.003583   
6  blues.00000.6.wav          0.379909         0.088827  0.130335  0.003166   
7  blues.00000.7.wav          0.331880         0.092119  0.140600  0.002546   
8  blues.00000.8.wav          0.347877         0.094209  0.133130  0.002538   
9  blues.00000.9.wav          0.358061         0.082957  0.115312  0.001846   

   spectral_centroid_mean  spectral_centroid_var  spectral_bandwidth_mean  \
0             1773.065032          167541.630869              1972.744388   
1             1816.693777           90525.690866              2010.051501   
2             1788.539719          111407.437613              2084.565132   
3             1655.289045          111952.284517              1960.039988   
4             1630.656199           79667.267654              1948.503884   
5             1994.915219          211700.619569              2152.767854   
6             1962.150096          177443.070045              2146.503479   
7             1701.890924           35678.130616              1979.387612   
8             1746.473502          138073.931244              1887.619723   
9             1763.948942           61493.423121              1874.195710   

   spectral_bandwidth_var  rolloff_mean  ...  mfcc16_var  mfcc17_mean  \
0           117335.771563   3714.560359  ...   39.687145    -3.241280   
1            65671.875673   3869.682242  ...   64.748276    -6.055294   
2            75124.921716   3997.639160  ...   67.336563    -1.768610   
3            82913.639269   3568.300218  ...   47.739452    -3.841155   
4            60204.020268   3469.992864  ...   30.336359     0.664582   
5            74263.873102   4371.985614  ...   31.448069    -3.448373   
6            98020.541422   4325.026668  ...   33.954071    -2.068194   
7            36670.725886   3625.280386  ...   38.456211    -3.637886   
8           117069.920049   3586.934721  ...   44.311455    -4.370029   
9            51944.921435   3505.522649  ...   43.967834    -3.448304   

   mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  mfcc19_var  mfcc20_mean  \
0   36.488243     0.722209   38.099152    -5.050335   33.618073    -0.243027   
1   40.677654     0.159015   51.264091    -2.837699   97.030830     5.784063   
2   28.348579     2.378768   45.717648    -1.938424   53.050835     2.517375   
3   28.337118     1.218588   34.770935    -3.580352   50.836224     3.630866   
4   45.880913     1.689446   51.363583    -3.392489   26.738789     0.536961   
5   34.284130    -0.416165   40.791092    -3.649625   32.457901     3.025218   
6   25.623655     1.428141   47.957699    -3.267124   39.382240     3.276939   
7   24.530296    -0.105148   26.716150    -2.016985   23.150423     0.210787   
8   29.873167     2.114592   33.843155    -2.264663   80.812393     3.758598   
9   48.671944     0.099792   41.839546    -7.677177   96.253654     0.791776   

   mfcc20_var  label  
0   43.771767  blues  
1   59.943081  blues  
2   33.105122  blues  
3   32.023678  blues  
4   29.146694  blues  
5   28.892687  blues  
6   25.999132  blues  
7   42.512966  blues  
8   97.618835  blues  
9   40.416420  blues  

[10 rows x 59 columns]

# one KD tree

In [4]:
tdata = data.drop(columns='label',axis=1)
tdata = tdata.drop(columns='filename',axis=1)
X = np.array(tdata.values.tolist())
sx = preprocessing.StandardScaler().fit(X)
ssx = sx.transform(X)
tree = KDTree(ssx, leaf_size=50)

In [5]:
q = 345
qlabel = data.iloc[q]['label']
dist, ind = tree.query([ssx[q]], k=6)
print(dist)
print(ind)
data.iloc[ind[0]]

[[0.         3.20949805 3.44671491 3.89820348 4.14537844 4.45676599]]
[[345 317 344 300 942 849]]


filename  chroma_stft_mean  chroma_stft_var  rms_mean   rms_var  \
345   disco.00045.wav          0.407335         0.082570  0.135482  0.002826   
317   disco.00017.wav          0.404499         0.079370  0.116129  0.003510   
344   disco.00044.wav          0.366914         0.085242  0.148973  0.002971   
300   disco.00000.wav          0.445477         0.087835  0.142184  0.004136   
942    rock.00042.wav          0.444428         0.080317  0.118999  0.001959   
849  reggae.00049.wav          0.370719         0.088069  0.132980  0.002237   

     spectral_centroid_mean  spectral_centroid_var  spectral_bandwidth_mean  \
345             2248.003751          840206.125964              2368.669507   
317             2564.319118          886671.208045              2669.929254   
344             2329.990134          493586.447786              2436.965460   
300             2297.869205          898837.892920              2565.714338   
942             2794.815529          611217.837696              2732.148131   
849             2322.063171          557758.351107              2803.754910   

     spectral_bandwidth_var  rolloff_mean  ...  mfcc16_var  mfcc17_mean  \
345           326708.179645   4609.537685  ...   30.940132    -3.284158   
317           294426.430093   5388.255250  ...   43.270554    -4.691309   
344           245189.899731   4644.094063  ...   39.588104    -2.896801   
300           192600.476879   4888.775343  ...   39.548061    -5.322056   
942           206382.809746   5878.322975  ...   35.954655    -5.021916   
849           268273.943330   5450.165291  ...   40.482159    -6.642506   

     mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  mfcc19_var  \
345   30.866360    -1.869772   37.330929    -0.713399   50.328873   
317   29.959862    -2.714943   38.920021    -1.851295   59.283787   
344   37.710480    -3.432507   47.447514    -2.565010   36.524147   
300   32.328892     1.239463   41.781643    -5.596891   41.700623   
942   30.488245    -2.397030   27.139633    -2.978907   27.836185   
849   39.731449    -4.406873   33.726353    -3.161338   31.566446   

     mfcc20_mean  mfcc20_var   label  
345    -0.551771   42.523273   disco  
317    -3.103202   30.024467   disco  
344    -3.041234   42.194416   disco  
300    -3.592718   30.864504   disco  
942    -4.951615   24.941542    rock  
849    -3.985336   39.104481  reggae  

[6 rows x 59 columns]

In [6]:
#query 3s piece
tdata_3 = data_3.drop(columns='label',axis=1)
tdata_3 = tdata_3.drop(columns='filename',axis=1)
X_3 = np.array(tdata_3.values.tolist())
sx_3 = preprocessing.StandardScaler().fit(X_3)
ssx_3 = sx.transform(X_3)
q = 234
qlabel = data_3.iloc[q]['label']
dist, ind = tree.query([ssx_3[q]], k=6)
print(dist)
print(ind)
data.iloc[ind[0]]


[[6.03770614 6.06655641 6.50614078 6.55932302 6.60250339 6.68309772]]
[[ 23 127 123 109 181 176]]


filename  chroma_stft_mean  chroma_stft_var  rms_mean  \
23       blues.00023.wav          0.280823         0.091157  0.102035   
127  classical.00027.wav          0.240693         0.083587  0.028415   
123  classical.00023.wav          0.267224         0.088496  0.017150   
109  classical.00009.wav          0.270524         0.082300  0.023803   
181  classical.00081.wav          0.266827         0.084227  0.016546   
176  classical.00076.wav          0.260388         0.084063  0.058816   

      rms_var  spectral_centroid_mean  spectral_centroid_var  \
23   0.003566             1209.987863          131778.372556   
127  0.000207              901.690663           27472.382486   
123  0.000046              983.724642           46995.862022   
109  0.000200             1216.187786          121041.376393   
181  0.000050             1213.971712           83056.685521   
176  0.001409             1340.642382           71733.166573   

     spectral_bandwidth_mean  spectral_bandwidth_var  rolloff_mean  ...  \
23               1497.691564            51624.607823   2521.741261  ...   
127              1171.783640            26470.879698   1456.338990  ...   
123              1404.022662            24439.937765   1852.729787  ...   
109              1582.826588            72868.681171   2560.003081  ...   
181              1539.592686            54396.267455   2163.887070  ...   
176              1539.044982            49838.665492   2522.515657  ...   

     mfcc16_var  mfcc17_mean  mfcc17_var  mfcc18_mean  mfcc18_var  \
23    45.263859    -2.985965   66.982353    -1.386169   82.635551   
127   49.832024     2.127288   75.944252     0.702086   53.507370   
123   71.723152     3.501278   96.612106     7.381740   88.338272   
109   79.411140    -0.660842   80.768044     1.160319  105.002167   
181   46.745155    -3.124706   54.713120    -0.213338   67.064110   
176   43.041641     0.657766   40.172104     1.477572   61.514114   

     mfcc19_mean  mfcc19_var  mfcc20_mean  mfcc20_var      label  
23      7.541378   93.393692    -3.035723   74.014458      blues  
127     1.027190   62.077988    -3.060726   98.877319  classical  
123     6.434403  109.966019     0.189756  113.283180  classical  
109    -0.618511   92.521919    -0.254033   88.053047  classical  
181     2.632269   75.738228     1.816808  102.780624  classical  
176    -1.836200   71.697411    -6.258352   83.414780  classical  

[6 rows x 59 columns]

In [5]:
sx = preprocessing.StandardScaler().fit(X)
ssx = sx.transform(X)
tree = KDTree(ssx, leaf_size=50)
acc = 0
rnum = 5
for q in range(1000):
    qlabel = data.iloc[q]['label']
    dist, ind = tree.query([ssx[q]], k=rnum+1)
    matched = data.iloc[ind[0]].where(data.label==qlabel).dropna(axis=0, how='all').shape[0]
    acc = acc + matched -1
    if q%50==0:
        print(str(q) + " done")
acc /= (1000*rnum)
print(acc)

0 done
50 done
100 done
150 done
200 done
250 done
300 done
350 done
400 done
450 done
500 done
550 done
600 done
650 done
700 done
750 done
800 done
850 done
900 done
950 done
0.5984


In [7]:
sx = preprocessing.StandardScaler().fit(X)
ssx = sx.transform(X)
tree = KDTree(ssx, leaf_size=50)
acc = 0
rnum = 7
for q in range(1000):
    qlabel = data.iloc[q]['label']
    dist, ind = tree.query([ssx[q]], k=rnum+1)
    matched = data.iloc[ind[0]].where(data.label==qlabel).dropna(axis=0, how='all').shape[0]
    acc = acc + matched -1
    if q%50==0:
        print(str(q) + " done")
acc /= (1000*rnum)
print(acc)

0 done
50 done
100 done
150 done
200 done
250 done
300 done
350 done
400 done
450 done
500 done
550 done
600 done
650 done
700 done
750 done
800 done
850 done
900 done
950 done
0.57


# 10 KDtree

In [21]:
map_label = {"blues":0, "classical":1, "country":2, "disco":3, "hiphop":4, "jazz":5, "metal":6, "pop":7, "reggae":8, "rock":9}
classes=["blues", "classical", "country", "disco", "hiphop", "jazz", "metal", "pop", "reggae", "rock"]
data = pd.read_csv("./data/features_30_sec.csv")
# data = data.iloc[0:, 2:]
data = data.drop(columns='length',axis=1)
music_lib = {}
for i in range(10):
    music_lib[classes[i]] = data.where(data.label==classes[i]).dropna(axis=0, how='all')
print(data.shape)
data.head(10)

(1000, 59)


filename  chroma_stft_mean  chroma_stft_var  rms_mean   rms_var  \
0  blues.00000.wav          0.350088         0.088757  0.130228  0.002827   
1  blues.00001.wav          0.340914         0.094980  0.095948  0.002373   
2  blues.00002.wav          0.363637         0.085275  0.175570  0.002746   
3  blues.00003.wav          0.404785         0.093999  0.141093  0.006346   
4  blues.00004.wav          0.308526         0.087841  0.091529  0.002303   
5  blues.00005.wav          0.302456         0.087532  0.103494  0.003981   
6  blues.00006.wav          0.291328         0.093981  0.141874  0.008803   
7  blues.00007.wav          0.307955         0.092903  0.131822  0.005531   
8  blues.00008.wav          0.408879         0.086512  0.142416  0.001507   
9  blues.00009.wav          0.273950         0.092316  0.081314  0.004347   

   spectral_centroid_mean  spectral_centroid_var  spectral_bandwidth_mean  \
0             1784.165850           1.297741e+05              2002.449060   
1             1530.176679           3.758501e+05              2039.036516   
2             1552.811865           1.564676e+05              1747.702312   
3             1070.106615           1.843559e+05              1596.412872   
4             1835.004266           3.433999e+05              1748.172116   
5             1831.993940           1.030482e+06              1729.653287   
6             1459.366472           4.378594e+05              1389.009131   
7             1451.667066           4.495682e+05              1577.270941   
8             1719.368948           1.632828e+05              2031.740381   
9             1817.150863           2.982361e+05              1973.773306   

   spectral_bandwidth_var  rolloff_mean  ...  mfcc16_var  mfcc17_mean  \
0            85882.761315   3805.839606  ...   52.420910    -1.690215   
1           213843.755497   3550.522098  ...   55.356403    -0.731125   
2            76254.192257   3042.260232  ...   40.598766    -7.729093   
3           166441.494769   2184.745799  ...   44.427753    -3.319597   
4            88445.209036   3579.757627  ...   86.099236    -5.454034   
5           201910.508633   3481.517592  ...   72.549225    -1.838263   
6           185023.239545   2795.610963  ...   83.248245   -10.913176   
7           168211.938804   2954.836760  ...   70.438438   -10.568935   
8           105542.718193   3782.316288  ...   50.563751    -7.041824   
9           114070.112591   3943.490565  ...   59.314602    -1.916804   

   mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  mfcc19_var  mfcc20_mean  \
0   36.524071    -0.408979   41.597103    -2.303523   55.062923     1.221291   
1   60.314529     0.295073   48.120598    -0.283518   51.106190     0.531217   
2   47.639427    -1.816407   52.382141    -3.439720   46.639660    -2.231258   
3   50.206673     0.636965   37.319130    -0.619121   37.259739    -3.407448   
4   75.269707    -0.916874   53.613918    -4.404827   62.910812   -11.703234   
5   68.702026    -2.783800   42.447453    -3.047909   39.808784    -8.109991   
6   56.902153    -6.971336   38.231800    -3.436505   48.235741    -6.483466   
7   52.090893   -10.784515   60.461330    -4.690678   65.547516    -8.630722   
8   28.894934     2.695248   36.889568     3.412305   33.698597    -2.715692   
9   58.418438    -2.292661   83.205231     2.881967   77.082222    -4.235203   

   mfcc20_var  label  
0   46.936035  blues  
1   45.786282  blues  
2   30.573025  blues  
3   31.949339  blues  
4   55.195160  blues  
5   46.311005  blues  
6   70.170364  blues  
7   56.401436  blues  
8   36.418430  blues  
9   91.468811  blues  

[10 rows x 59 columns]

In [22]:
tdata = data.drop(columns='label',axis=1)
tdata = tdata.drop(columns='filename',axis=1)
X = np.array(tdata.values.tolist())
slib = preprocessing.StandardScaler().fit(X)
sslib = slib.transform(X)
label_tree = {}
for i in range(10):
    label_tree[classes[i]] = KDTree(sslib[i*100:(i+1)*100], leaf_size=50)

In [24]:
q =345
qdata = sslib[q]
data.iloc[[q]]
qlabel = data.iloc[q]['label']
print(qlabel)
dist, ind = label_tree[qlabel].query([qdata], k=6)
print(dist)
print(ind)
music_lib[qlabel].iloc[ind[0]]

disco
[[0.         3.20949805 3.44671491 3.89820348 4.62602313 4.63368959]]
[[45 17 44  0 15 41]]


filename  chroma_stft_mean  chroma_stft_var  rms_mean   rms_var  \
345  disco.00045.wav          0.407335         0.082570  0.135482  0.002826   
317  disco.00017.wav          0.404499         0.079370  0.116129  0.003510   
344  disco.00044.wav          0.366914         0.085242  0.148973  0.002971   
300  disco.00000.wav          0.445477         0.087835  0.142184  0.004136   
315  disco.00015.wav          0.414912         0.079519  0.215978  0.002113   
341  disco.00041.wav          0.355709         0.089576  0.175499  0.003428   

     spectral_centroid_mean  spectral_centroid_var  spectral_bandwidth_mean  \
345             2248.003751          840206.125964              2368.669507   
317             2564.319118          886671.208045              2669.929254   
344             2329.990134          493586.447786              2436.965460   
300             2297.869205          898837.892920              2565.714338   
315             2362.199995          691724.630503              2806.725962   
341             1776.084333          619392.460611              2452.269279   

     spectral_bandwidth_var  rolloff_mean  ...  mfcc16_var  mfcc17_mean  \
345           326708.179645   4609.537685  ...   30.940132    -3.284158   
317           294426.430093   5388.255250  ...   43.270554    -4.691309   
344           245189.899731   4644.094063  ...   39.588104    -2.896801   
300           192600.476879   4888.775343  ...   39.548061    -5.322056   
315           318506.781960   5439.015654  ...   35.843262    -2.498974   
341           308231.408446   3874.078043  ...   41.721691    -5.759640   

     mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  mfcc19_var  \
345   30.866360    -1.869772   37.330929    -0.713399   50.328873   
317   29.959862    -2.714943   38.920021    -1.851295   59.283787   
344   37.710480    -3.432507   47.447514    -2.565010   36.524147   
300   32.328892     1.239463   41.781643    -5.596891   41.700623   
315   43.612232     0.537371   32.720196     2.519058   37.588688   
341   49.451294     0.707102   39.217903     0.269818   41.051395   

     mfcc20_mean  mfcc20_var  label  
345    -0.551771   42.523273  disco  
317    -3.103202   30.024467  disco  
344    -3.041234   42.194416  disco  
300    -3.592718   30.864504  disco  
315    -3.543926   46.879646  disco  
341    -2.286904   46.264408  disco  

[6 rows x 59 columns]